// @keyframes puff-in-center {0% { transform: scale(2); filter: blur(4px); opacity: 0 }100% { transform: scale(1); filter: blur(0); opacity: 1 }}
// @keyframes puff-in-bottom {0% { transform: scale(2); transform-origin: 50% 100%; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 50% 100%; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-br {0% { transform: scale(2); transform-origin: 100% 100%; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 100% 100%; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-ver {0% { transform: scaleY(2); filter: blur(4px); opacity: 0 }100% { transform: scaleY(1); filter: blur(0); opacity: 1 }}
// @keyframes puff-in-right {0% { transform: scale(2); transform-origin: 100% 50%; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 100% 50%; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-hor {0% { transform: scaleX(2); filter: blur(4px); opacity: 0 }100% { transform: scaleX(1); filter: blur(0); opacity: 1 }}
// @keyframes puff-in-tr {0% { transform: scale(2); transform-origin: 100% 0; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 100% 0; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-tl {0% { transform: scale(2); transform-origin: 0 0; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 0 0; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-top {0% { transform: scale(2); transform-origin: 50% 0; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 50% 0; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-left {0% { transform: scale(2); transform-origin: 0 50%; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 0 50%; filter: blur(0); opacity: 1 }}
// @keyframes puff-in-bl {0% { transform: scale(2); transform-origin: 0 100%; filter: blur(4px); opacity: 0 }100% { transform: scale(1); transform-origin: 0 100%; filter: blur(0); opacity: 1 }}